version: "3"
services:
  order_mgmt:
    build: ./orders
    ports:
      - "5001:5001"
    networks:
      - app_network

  product_mgmt:
    build: ./products
    ports:
      - "5002:5002"
    networks:
      - app_network

  user_mgmt:
    build: ./users
    ports:
      - "5003:5003"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
