apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orders
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer