apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: products
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
